Install cv2 4.4
---



In [2]:
!pip install opencv-contrib-python==4.4.0.44

## Library

In [64]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
import pickle
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

## Mount Drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Path

In [59]:
folder1=r"drive/MyDrive/CV_CP/traffic/traffic_pos"
folder2=r"drive/MyDrive/CV_CP/traffic/kids_playing_pos"
folder3=r"drive/MyDrive/CV_CP/traffic/traffic_signal"


## Img Processing + SIFT (+ve)

In [8]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(150,230)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    # normalize
    descriptors = preprocessing.normalize(descriptors)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('drive/MyDrive/CV_CP/traffic/t_pos.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (467, 128)
descriptor shape  1  :  (387, 128)
descriptor shape  2  :  (372, 128)
descriptor shape  3  :  (203, 128)
descriptor shape  4  :  (432, 128)
descriptor shape  5  :  (312, 128)
descriptor shape  6  :  (700, 128)
descriptor shape  7  :  (305, 128)
descriptor shape  8  :  (529, 128)
descriptor shape  9  :  (629, 128)
descriptor shape  10  :  (346, 128)
descriptor shape  11  :  (642, 128)
descriptor shape  12  :  (431, 128)
descriptor shape  13  :  (557, 128)
descriptor shape  14  :  (436, 128)
descriptor shape  15  :  (598, 128)
descriptor shape  16  :  (480, 128)
descriptor shape  17  :  (426, 128)
descriptor shape  18  :  (498, 128)
descriptor shape  19  :  (276, 128)
descriptor shape  20  :  (631, 128)
descriptor shape  21  :  (858, 128)
descriptor shape  22  :  (714, 128)
descriptor shape  23  :  (521, 128)
descriptor shape  24  :  (365, 128)
descriptor shape  25  :  (506, 128)
descriptor shape  26  :  (502, 128)
descriptor shape  27  :  (577, 128)
de

## Feature vec (1)

In [9]:
data1 = pd.read_csv(r'drive/MyDrive/CV_CP/traffic/t_pos.csv',header=None)
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

#data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0         1         2    ...       125       126       127
0        0.021436  0.042872  0.099384  ...  0.000000  0.000000  0.000000
1        0.154393  0.042995  0.023452  ...  0.000000  0.000000  0.000000
2        0.000000  0.000000  0.000000  ...  0.097793  0.033250  0.060632
3        0.101624  0.261877  0.140710  ...  0.015634  0.019543  0.035177
4        0.037144  0.099701  0.248276  ...  0.000000  0.000000  0.000000
...           ...       ...       ...  ...       ...       ...       ...
1503678  0.011711  0.003904  0.005855  ...  0.005855  0.000000  0.003904
1503679  0.263441  0.263441  0.015611  ...  0.105376  0.101474  0.025368
1503680  0.000000  0.000000  0.000000  ...  0.132731  0.089788  0.031231
1503681  0.000000  0.000000  0.000000  ...  0.007823  0.000000  0.011734
1503682  0.000000  0.000000  0.216334  ...  0.000000  0.000000  0.000000

[1503683 rows x 128 columns]

## Img Processing + SIFT (2)


In [10]:
i=0
for filename in os.listdir(folder2):
    
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(150,230)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    # normalize
    descriptors = preprocessing.normalize(descriptors)
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('drive/MyDrive/CV_CP/traffic/kids_pos.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (459, 128)
descriptor shape  1  :  (325, 128)
descriptor shape  2  :  (843, 128)
descriptor shape  3  :  (242, 128)
descriptor shape  4  :  (535, 128)
descriptor shape  5  :  (540, 128)
descriptor shape  6  :  (582, 128)
descriptor shape  7  :  (451, 128)
descriptor shape  8  :  (344, 128)
descriptor shape  9  :  (511, 128)
descriptor shape  10  :  (227, 128)
descriptor shape  11  :  (448, 128)
descriptor shape  12  :  (284, 128)
descriptor shape  13  :  (745, 128)
descriptor shape  14  :  (305, 128)
descriptor shape  15  :  (393, 128)
descriptor shape  16  :  (353, 128)
descriptor shape  17  :  (94, 128)
descriptor shape  18  :  (327, 128)
descriptor shape  19  :  (353, 128)
descriptor shape  20  :  (402, 128)
descriptor shape  21  :  (540, 128)
descriptor shape  22  :  (547, 128)
descriptor shape  23  :  (173, 128)
descriptor shape  24  :  (477, 128)
descriptor shape  25  :  (254, 128)
descriptor shape  26  :  (162, 128)
descriptor shape  27  :  (444, 128)
des

In [12]:
data2= pd.read_csv(r'drive/MyDrive/CV_CP/traffic/kids_pos.csv',header=None)
#data2=data2.astype(np.uint8)
data2

0         1         2    ...       125       126       127
0        0.226177  0.052645  0.000000  ...  0.079942  0.001950  0.005849
1        0.027332  0.007809  0.009761  ...  0.009761  0.005857  0.109326
2        0.103603  0.035186  0.009774  ...  0.019548  0.005864  0.007819
3        0.048784  0.000000  0.000000  ...  0.021465  0.003903  0.044881
4        0.023405  0.013653  0.001950  ...  0.023405  0.005851  0.023405
...           ...       ...       ...  ...       ...       ...       ...
1099165  0.019519  0.128822  0.015615  ...  0.019519  0.001952  0.001952
1099166  0.017574  0.029291  0.033196  ...  0.009764  0.000000  0.000000
1099167  0.048760  0.169684  0.122874  ...  0.007802  0.003901  0.000000
1099168  0.023397  0.040944  0.134531  ...  0.019497  0.003899  0.000000
1099169  0.009763  0.000000  0.000000  ...  0.171825  0.087865  0.078102

[1099170 rows x 128 columns]

## Img Processing + SIFT (3)

In [13]:
i=0
for filename in os.listdir(folder3):
    
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(150,230)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    # normalize
    descriptors = preprocessing.normalize(descriptors)
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('drive/MyDrive/CV_CP/traffic/t_neg.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (191, 128)
descriptor shape  1  :  (154, 128)
descriptor shape  2  :  (191, 128)
descriptor shape  3  :  (169, 128)
descriptor shape  4  :  (107, 128)
descriptor shape  5  :  (85, 128)
descriptor shape  6  :  (85, 128)
descriptor shape  7  :  (28, 128)
descriptor shape  8  :  (198, 128)
descriptor shape  9  :  (164, 128)
descriptor shape  10  :  (249, 128)
descriptor shape  11  :  (173, 128)
descriptor shape  12  :  (233, 128)
descriptor shape  13  :  (173, 128)
descriptor shape  14  :  (53, 128)
descriptor shape  15  :  (19, 128)
descriptor shape  16  :  (212, 128)
descriptor shape  17  :  (232, 128)
descriptor shape  18  :  (53, 128)
descriptor shape  19  :  (53, 128)
descriptor shape  20  :  (122, 128)
descriptor shape  21  :  (173, 128)
descriptor shape  22  :  (149, 128)
descriptor shape  23  :  (184, 128)
descriptor shape  24  :  (165, 128)
descriptor shape  25  :  (135, 128)
descriptor shape  26  :  (181, 128)
descriptor shape  27  :  (41, 128)
descriptor

In [14]:
data3= pd.read_csv(r'drive/MyDrive/CV_CP/traffic/t_neg.csv',header=None)
#data3=data3.astype(np.uint8)
data3

0         1         2    ...       125       126       127
0       0.068285  0.031216  0.000000  ...  0.000000  0.000000  0.000000
1       0.000000  0.000000  0.000000  ...  0.005861  0.000000  0.005861
2       0.000000  0.000000  0.001953  ...  0.000000  0.001953  0.005859
3       0.103490  0.080058  0.017574  ...  0.001953  0.025384  0.001953
4       0.021484  0.236328  0.212890  ...  0.056641  0.052734  0.056641
...          ...       ...       ...  ...       ...       ...       ...
353760  0.001951  0.000000  0.000000  ...  0.000000  0.000000  0.001951
353761  0.001956  0.000000  0.001956  ...  0.000000  0.000000  0.000000
353762  0.001958  0.000000  0.005874  ...  0.000000  0.000000  0.000000
353763  0.087872  0.230420  0.000000  ...  0.000000  0.000000  0.000000
353764  0.003906  0.001953  0.001953  ...  0.000000  0.000000  0.000000

[353765 rows x 128 columns]

## Combined vec

In [15]:
data=data1.append([data2,data3])
csv_data=data.to_csv('drive/MyDrive/CV_CP/traffic/Sift_Final.csv', mode='a', header=False,index=False)
data

0         1         2    ...       125       126       127
0       0.021436  0.042872  0.099384  ...  0.000000  0.000000  0.000000
1       0.154393  0.042995  0.023452  ...  0.000000  0.000000  0.000000
2       0.000000  0.000000  0.000000  ...  0.097793  0.033250  0.060632
3       0.101624  0.261877  0.140710  ...  0.015634  0.019543  0.035177
4       0.037144  0.099701  0.248276  ...  0.000000  0.000000  0.000000
...          ...       ...       ...  ...       ...       ...       ...
353760  0.001951  0.000000  0.000000  ...  0.000000  0.000000  0.001951
353761  0.001956  0.000000  0.001956  ...  0.000000  0.000000  0.000000
353762  0.001958  0.000000  0.005874  ...  0.000000  0.000000  0.000000
353763  0.087872  0.230420  0.000000  ...  0.000000  0.000000  0.000000
353764  0.003906  0.001953  0.001953  ...  0.000000  0.000000  0.000000

[2956618 rows x 128 columns]

In [4]:
data = pd.read_csv('drive/MyDrive/CV_CP/traffic/Sift_Final.csv')

## Kmeans

In [5]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)

KMeans(n_clusters=5)

In [6]:
# save the model to disk
filename = 'drive/MyDrive/CV_CP/traffic/Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [60]:
# load file from disk
file = 'drive/MyDrive/CV_CP/traffic/Kmeans_CL_5_Model.sav'
kmeans = pickle.load(open(file, 'rb'))

In [17]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])

print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([433965, 545470, 853942, 525565, 597675]), array([0, 1, 2, 3, 4, 5])) 



In [18]:
#performing kmeans prediction of the entire Staircase dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    
    #resize image
    resize=(150,230)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    descriptors = preprocessing.normalize(descriptors)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i
csv_data=Output.to_csv('drive/MyDrive/CV_CP/traffic/FinalTraffic.csv', mode='a',header=False,index=False)

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not 

In [19]:
#performing kmeans prediction of the entire Kids Playing dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(150,230)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    descriptors = preprocessing.normalize(descriptors)
    
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('drive/MyDrive/CV_CP/traffic/FinalKids.csv', mode='a',header=False,index=False)

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not 

In [20]:
#performing kmeans prediction of the entire Negative dataset with the pretrained kmeans model

#initialising i=2; as its the 3rd class
i=2
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(100,133)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    descriptors = preprocessing.normalize(descriptors)
    
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('drive/MyDrive/CV_CP/traffic/FinalNegTraffic.csv', mode='a',header=False,index=False)

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not 

In [26]:
#Displaying the kmeans predicted data
print("Traffic")
dat1= pd.read_csv(r'drive/MyDrive/CV_CP/traffic/FinalTraffic.csv',header=None)
print(dat1)

Traffic
       0    1    2    3    4  5
0     49   32  177  117   92  0
1     72   31  132   70   82  0
2     55   75   87   81   74  0
3     22   54   57   41   29  0
4     71   44  155   86   76  0
...   ..  ...  ...  ...  ... ..
2995  68   52  191  105  115  0
2996  57  121  174  106  109  0
2997  73  107  142   94  113  0
2998  51   97  131   94  112  0
2999  97   66  212  112  150  0

[3000 rows x 6 columns]


In [27]:
#Displaying the kmeans predicted data
print("Kids Playing")
dat2= pd.read_csv(r'drive/MyDrive/CV_CP/traffic/FinalKids.csv',header=None)
print(dat2)

Kids Playing
        0    1    2    3    4  5
0      70   68  142   85   94  1
1      59   69   98   45   54  1
2     149  133  186  155  220  1
3      28   57   60   46   51  1
4      98  132  127   67  111  1
...   ...  ...  ...  ...  ... ..
2995   70   88  152   88   88  1
2996   59  108  126   84  107  1
2997   35  108  165   78   74  1
2998   34   78   91   63   60  1
2999   21   46   23   14   23  1

[3000 rows x 6 columns]


In [28]:
#Displaying the kmeans predicted data
print("Traffic Neg")
dat3= pd.read_csv(r'drive/MyDrive/CV_CP/traffic/FinalNegTraffic.csv',header=None)
print(dat3)

Traffic Neg
       0   1   2   3   4  5
0     36  44  69  56  48  2
1     33  30  65  37  44  2
2     47  42  88  52  78  2
3     15  39  41  18  27  2
4     44  59  60  34  73  2
...   ..  ..  ..  ..  .. ..
2995  33  36  67  51  52  2
2996  19  53  56  37  42  2
2997  14  60  72  46  40  2
2998  20  49  52  29  41  2
2999  17  30  18  10  21  2

[3000 rows x 6 columns]


In [29]:
#appending All classes into 1 csv file

A=dat1.append([dat2, dat3])

csv_data=A.to_csv('drive/MyDrive/CV_CP/traffic/FinalFV.csv', mode='a',header=False,index=False)

In [30]:
A

0   1    2    3   4  5
0     49  32  177  117  92  0
1     72  31  132   70  82  0
2     55  75   87   81  74  0
3     22  54   57   41  29  0
4     71  44  155   86  76  0
...   ..  ..  ...  ...  .. ..
2995  33  36   67   51  52  2
2996  19  53   56   37  42  2
2997  14  60   72   46  40  2
2998  20  49   52   29  41  2
2999  17  30   18   10  21  2

[9000 rows x 6 columns]

In [31]:
x = A.iloc[:,0:5].values
x

array([[ 49,  32, 177, 117,  92],
       [ 72,  31, 132,  70,  82],
       [ 55,  75,  87,  81,  74],
       ...,
       [ 14,  60,  72,  46,  40],
       [ 20,  49,  52,  29,  41],
       [ 17,  30,  18,  10,  21]])

In [32]:
y = A.iloc[:,5].values
y

array([0, 0, 0, ..., 2, 2, 2])

In [33]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [34]:
Dhoni

array([[-0.09910198, -1.10083308,  1.25152009,  1.40430116,  0.4757232 ],
       [ 0.64491769, -1.13727164,  0.47892854,  0.14703478,  0.22590211],
       [ 0.09499011,  0.46602484, -0.293663  ,  0.44128861,  0.02604524],
       ...,
       [-1.23130584, -0.0805535 , -0.55119351, -0.49497359, -0.82334647],
       [-1.03721375, -0.48137762, -0.89456753, -0.94972951, -0.79836436],
       [-1.1342598 , -1.1737102 , -1.47830336, -1.45798614, -1.29800653]])

In [35]:
from sklearn.decomposition import PCA

In [36]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [37]:
Bhumi = pca.transform(Dhoni)

In [38]:
Bhumi

array([[ 1.21574337, -1.45190916, -1.15838946,  0.11120296, -0.2145393 ],
       [ 0.42574909, -1.294404  ,  0.26424314,  0.27558954,  0.09386755],
       [ 0.24724086,  0.43100876,  0.01593523, -0.1623601 , -0.48408976],
       ...,
       [-1.50450291,  0.31031436, -0.62054754, -0.06563221, -0.01022903],
       [-1.89543698, -0.00300691, -0.12260933, -0.16331475,  0.11298013],
       [-2.89834385, -0.45695474,  0.20669304, -0.09010712,  0.00450561]])

In [39]:
Bhumi = pd.DataFrame(Bhumi)

In [40]:
Bhumi

0         1         2         3         4
0     1.215743 -1.451909 -1.158389  0.111203 -0.214539
1     0.425749 -1.294404  0.264243  0.275590  0.093868
2     0.247241  0.431009  0.015935 -0.162360 -0.484090
3    -1.770658  0.153603 -0.284487  0.113729 -0.194608
4     0.858061 -0.919965 -0.133629  0.558893 -0.052299
...        ...       ...       ...       ...       ...
8995 -1.271225 -0.649637 -0.121036 -0.143472 -0.172072
8996 -1.722333  0.105084 -0.265916 -0.172856  0.007379
8997 -1.504503  0.310314 -0.620548 -0.065632 -0.010229
8998 -1.895437 -0.003007 -0.122609 -0.163315  0.112980
8999 -2.898344 -0.456955  0.206693 -0.090107  0.004506

[9000 rows x 5 columns]

In [41]:
Bhumi.shape

(9000, 5)

In [42]:
print(pca.explained_variance_ratio_) 

[0.7449765  0.16321673 0.06692869 0.01426297 0.01061511]


In [43]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [44]:
# save the model to disk
filename = 'drive/MyDrive/CV_CP/traffic/PCA_3_Model.sav'
pickle.dump(pca, open(filename, 'wb'))

In [45]:
Bhumi = pca.transform(Dhoni)

In [46]:
Bhumi

array([[ 1.21574337, -1.45190916, -1.15838946],
       [ 0.42574909, -1.294404  ,  0.26424314],
       [ 0.24724086,  0.43100876,  0.01593523],
       ...,
       [-1.50450291,  0.31031436, -0.62054754],
       [-1.89543698, -0.00300691, -0.12260933],
       [-2.89834385, -0.45695474,  0.20669304]])

In [47]:
Bhumi.shape

(9000, 3)

In [48]:
print(pca.explained_variance_ratio_) 

[0.7449765  0.16321673 0.06692869]


In [49]:
Bhumi = pd.DataFrame(Bhumi)

In [50]:
Bhumi

0         1         2
0     1.215743 -1.451909 -1.158389
1     0.425749 -1.294404  0.264243
2     0.247241  0.431009  0.015935
3    -1.770658  0.153603 -0.284487
4     0.858061 -0.919965 -0.133629
...        ...       ...       ...
8995 -1.271225 -0.649637 -0.121036
8996 -1.722333  0.105084 -0.265916
8997 -1.504503  0.310314 -0.620548
8998 -1.895437 -0.003007 -0.122609
8999 -2.898344 -0.456955  0.206693

[9000 rows x 3 columns]

In [51]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [52]:
B

0         1         2  0
0     1.215743 -1.451909 -1.158389  0
1     0.425749 -1.294404  0.264243  0
2     0.247241  0.431009  0.015935  0
3    -1.770658  0.153603 -0.284487  0
4     0.858061 -0.919965 -0.133629  0
...        ...       ...       ... ..
8995 -1.271225 -0.649637 -0.121036  2
8996 -1.722333  0.105084 -0.265916  2
8997 -1.504503  0.310314 -0.620548  2
8998 -1.895437 -0.003007 -0.122609  2
8999 -2.898344 -0.456955  0.206693  2

[9000 rows x 4 columns]

In [53]:
csv_data=B.to_csv('drive/MyDrive/CV_CP/traffic/FinalPCAFV.csv', mode='a',header=False,index=False)

# Training ,Testing & Classification

In [54]:
data= pd.read_csv(r'drive/MyDrive/CV_CP/traffic/FinalPCAFV.csv',header=None)
data

0         1         2  3
0     1.215743 -1.451909 -1.158389  0
1     0.425749 -1.294404  0.264243  0
2     0.247241  0.431009  0.015935  0
3    -1.770658  0.153603 -0.284487  0
4     0.858061 -0.919965 -0.133629  0
...        ...       ...       ... ..
8995 -1.271225 -0.649637 -0.121036  2
8996 -1.722333  0.105084 -0.265916  2
8997 -1.504503  0.310314 -0.620548  2
8998 -1.895437 -0.003007 -0.122609  2
8999 -2.898344 -0.456955  0.206693  2

[9000 rows x 4 columns]

In [55]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[ 1.21574337 -1.45190916 -1.15838946]
 [ 0.42574909 -1.294404    0.26424314]
 [ 0.24724086  0.43100876  0.01593523]
 ...
 [-1.50450291  0.31031436 -0.62054754]
 [-1.89543698 -0.00300691 -0.12260933]
 [-2.89834385 -0.45695474  0.20669304]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
8995    2
8996    2
8997    2
8998    2
8999    2
Name: 3, Length: 9000, dtype: int64


In [56]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

## Decision Tree Classifier

In [57]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
#training the model with the Training Variables 
model1.fit(x_train, y_train)

#storing model into disk
filename = 'drive/MyDrive/CV_CP/traffic/model1.sav'
pickle.dump(model1, open(filename, 'wb'))
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

Decision Tree Results
Decision Tree Accuracy:  77.05555555555556 %


In [68]:
# load file from disk
file = 'drive/MyDrive/CV_CP/traffic/model1.sav'
model1 = pickle.load(open(file, 'rb'))

##Recognition & Validation

In [70]:
# prediction for multiple images
folder4 = r"drive/MyDrive/CV_CP/traffic/test"
result = []

for filename in os.listdir(folder4):
    #path
    path=os.path.join(folder4,filename)
    data = []
    #Repeated the process of image pre-processing and feature extraction
    a=cv2.imread(path)
    resize=(150,230)

    #resize image
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)

    descriptors = preprocessing.normalize(out) # normalize
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("Descriptor Shape:",out.shape)

    #initialise Kmeans and create 5 clusters
    test_kmeans = KMeans(n_clusters=5)
    test_kmeans.fit(out)

    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=test_kmeans.predict(array_double)

    #get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2,3,4,5])

    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])

    Output = pd.DataFrame(data)
    print("Histogram:\n",Output)

    MuktaS = StandardScaler()
    Mukta = MuktaS.fit_transform(Output)

    MB = pca.transform(Mukta)

    #prediction
    y_pred1 = model1.predict(MB)

    #prints the prediction of the class
    result.append(y_pred1)

Descriptor Shape: (96, 128)


ValueError: ignored

In [66]:
result

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),

In [ ]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [ ]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [ ]:
Mukta.shape

(1, 5)

In [ ]:
MB = pca.transform(Mukta)

In [ ]:
MB.shape

(1, 3)

In [ ]:
MB

array([[-1.67846643e-16,  2.73213394e-17, -2.69934858e-16]])

In [ ]:
#prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[0]


## SVC

In [71]:
# SVC [radial basis fun]
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [72]:
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [73]:
Dhoni_LK

SVC()

In [74]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [75]:
y_pred_LK

array([1, 2, 1, ..., 2, 2, 2])

In [76]:
from sklearn.metrics import confusion_matrix

In [77]:
confusion_matrix(y_test, y_pred_LK)

array([[421, 137,  37],
       [ 69, 428, 100],
       [  4,  26, 578]])

In [78]:
from sklearn.metrics import accuracy_score

In [80]:
accuracy_score(y_test, y_pred_LK)

0.7927777777777778

In [81]:
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[1]


## Random forest

In [82]:
#Random Forest CLassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='log2',
                                max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, 
                                n_jobs=None, random_state=2, verbose=0, warm_start=False, class_weight=None, 
                                ccp_alpha=0.0, max_samples=None)
filename = 'model4.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
#Results
print("RandomF Results")
print("RandomF Accuracy: ",accuracy_score(y_test, y_pred4)*100,"%")

RandomF Results
RandomF Accuracy:  79.83333333333333 %


## KNN

In [116]:
#knn
from sklearn.neighbors import KNeighborsClassifier

#KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train )
ypred = knn.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, ypred ))



Accuracy: 0.7611111111111111


In [84]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"/content/drive/MyDrive/CV_CP/traffic/kids_playing_pos/img7.jpg"

#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
#resize image
resize=(150,230)
img=cv2.resize(a,resize)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)
descriptors = preprocessing.normalize(descriptors)# normalize

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)
out = preprocessing.normalize(out) 
#initialise Kmeans and create 5 clusters



#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (376, 128)
Histogram:
     0    1   2   3   4
0  63  102  80  63  68


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  "X does not have valid feature names, but"


In [85]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [86]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [87]:
Mukta.shape

(1, 5)

In [88]:
MB = pca.transform(Mukta)

In [89]:
MB.shape

(1, 3)

In [90]:
MB

array([[-8.82432536e-17,  7.71542802e-17, -2.09384272e-18]])

In [91]:
# decision tree prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[1]


In [117]:
#knn prediction
print(knn.predict(MB))

[1]


In [94]:
from sklearn.metrics import accuracy_score

In [95]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='linear')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [96]:
y_pred_LK = Dhoni_LK.predict(x_test)
accuracy_score(y_test, y_pred_LK)

0.7838888888888889

In [97]:

DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [98]:
y_pred_LK = Dhoni_LK.predict(x_test)
accuracy_score(y_test, y_pred_LK)

0.7927777777777778

In [99]:
DhoniSVM_LK = SVC(kernel='poly')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [100]:
y_pred_LK = Dhoni_LK.predict(x_test)
accuracy_score(y_test, y_pred_LK)

0.7411111111111112

In [101]:
Dhoni_LK

SVC(kernel='poly')

In [102]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [103]:
y_pred_LK

array([1, 2, 1, ..., 2, 2, 2])

In [104]:
from sklearn.metrics import confusion_matrix

In [105]:
confusion_matrix(y_test, y_pred_LK)

array([[340, 224,  31],
       [ 44, 483,  70],
       [ 16,  81, 511]])

In [106]:
from sklearn.metrics import accuracy_score

In [107]:
accuracy_score(y_test, y_pred_LK)

0.7411111111111112

In [108]:
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[1]


In [109]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100)
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
#Results
print("RandomF Results")
print("RandomF Accuracy: ",accuracy_score(y_test, y_pred4)*100,"%")

RandomF Results
RandomF Accuracy:  80.11111111111111 %


In [110]:
predict=model4.predict(MB)
predict

array([1])

In [111]:
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(x_train,y_train)

#
y_pred=logreg.predict(x_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7744444444444445


In [112]:
predict1=logreg.predict(MB)
predict1

array([1])